export const dummyDataID = {
  Title: 'Avengers: Endgame',
  Year: '2019',
  Rated: 'PG-13',
  Released: '26 Apr 2019',
  Runtime: '181 min',
  Genre: 'Action, Adventure, Drama',
  Director: 'Anthony Russo, Joe Russo',
  Writer: 'Christopher Markus, Stephen McFeely, Stan Lee',
  Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
  Plot: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
  Language: 'English, Japanese, Xhosa, German',
  Country: 'United States',
  Awards: 'Nominated for 1 Oscar. 70 wins & 132 nominations total',
  Poster:
    'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg',
  Ratings: [
    {
      Source: 'Internet Movie Database',
      Value: '8.4/10',
    },
    {
      Source: 'Rotten Tomatoes',
      Value: '94%',
    },
    {
      Source: 'Metacritic',
      Value: '78/100',
    },
  ],
  Metascore: '78',
  imdbRating: '8.4',
  imdbVotes: '999,441',
  imdbID: 'tt4154796',
  Type: 'movie',
  DVD: '30 Jul 2019',
  BoxOffice: '$858,373,000',
  Production: 'N/A',
  Website: 'N/A',
  Response: 'True',
};
